# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:  
  - job: Build
    displayName: Build Maven Project
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

 
  - deployment: VMDeploy
    displayName: web
  # Use `dependsOn` if you are including the deployment job in the same pipeline with the Job to Build
    dependsOn: Build  
    environment:
      name:  VMenv
      resourceType: VirtualMachine
      tags: web, linux
    strategy:
      rolling:
        maxParallel: 2  #for percentages, mention as x%
        preDeploy:
          steps:
          - download: current
            artifact: drop
          - script: echo initialize, cleanup, backup, install certs
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                sudo java -jar '$(Pipeline.Workspace)/drop/target/*.jar'

          # - task: IISWebAppDeploymentOnMachineGroup@0
          #   displayName: 'Deploy application to Website'
          #   inputs:
          #     WebSiteName: 'Default Web Site'
          #     Package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
        routeTraffic:
          steps:
          - script: echo routing traffic
        postRouteTraffic:
          steps:
          - script: echo health check post-route traffic
        on:
          failure:
            steps:
            - script: echo Restore from backup! This is on failure
          success:
            steps:
            - script: echo Notify! This is on success
