# Maven
# Build your Java projects and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation - Docker Hub/ACR/...
  dockerRegistryServiceConnection: 'bfcbc9a8-079f-469d-889b-db8b10b4eb59'
  # Kubernetes service connection
  kubernetesServiceConnection: '5f552435-78fd-4ba0-b3ce-9d63384ca426'
  # Docker repository image full path
  imageRepositoryFullPath: 'aksdockersample/aks-docker-sample'
  # docker file path in the github repo
  dockerfilePath: 'dockerfile'  
  # Kubernetes Namespace
  k8sNamespace: 'default'
  # kubernetes manifest file
  k8sManifests: 'AKSDeployment.yaml'
  # Agent Pool Name
  poolName: 'Hosted Ubuntu 1604'

- stage: Build
  displayName: 'Build stage'
  jobs:
    - job: MavenBuild
      steps:
      - task: Maven@3
        displayName: 'Maven $(mavenPOMFile)'
        inputs:
          mavenPomFile: pom.xml
      
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**/*.jar'
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts: drop'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
    
    - deployment: Deploy
      displayName: Deploy job
      # can not w euse variables?
      dependsOn: MavenBuild
      environment: 'SmartHotel'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Download Build Artifacts'
              inputs:
                artifactName: drop
            - task: AzureWebApp@1
              displayName: 'Azure Web App Deploy: LinuxJSEApp'
              inputs:
                azureSubscription: 'RMPM'
                appType: webAppLinux
                appName: LinuxJSEApp
                package: '$(build.artifactstagingdirectory)/**/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar'

- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    # can not w euse variables?
    environment: 'SmartHotel.notifications'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'git clone https://github.com/madhuv-msft/DockerAKSTutorial.git . ;'
              errorActionPreference: 'continue'
          - task: KubernetesManifest@0
            displayName: 'Deploy to Kubernetes cluster'
            inputs:
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              action: 'deploy'
              namespace: $(k8sNamespace)
              manifests: $(k8sManifests)
              containers: $(imageRepositoryFullPath):$(Build.BuildId)

#        runtimeStack: 'null'
#        startUpCommand: 'mvn azure-webapp:deploy'
#       startUpCommand: 'java -jar spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar  --server.port=80'
#        startUpCommand: 'mvnw spring-boot:run'
